spring:
  application:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@

  jackson:
    property-naming-strategy: SNAKE_CASE
  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  shutdown: graceful


logging:
  level:
    .: ERROR